// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SciTrack.Api.Data;

#nullable disable

namespace SciTrack.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SciTrack.Api.Models.DeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("HaoMonKhauHaoLienQuan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("KetQuaDeTaiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KinhPhiGiaoKhoan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("KinhPhiThucHien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("KinhPhiVatTu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaSoDeTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatTaiSan")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuyetDinhLienQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyetDinhXuLyTaiSan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeTai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KetQuaDeTaiId");

                    b.ToTable("DeTais");
                });

            modelBuilder.Entity("SciTrack.Api.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChiPhiChuyenMon")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ChiPhiTuKetQuaDeTai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ChiPhiTuTrangThietBi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("LoiNhuan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNghiemThu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDoiTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongGiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("SciTrack.Api.Models.KetQuaDeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CacHopDongSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DinhGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaTriConLai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaSoKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KetQuaDeTais");
                });

            modelBuilder.Entity("SciTrack.Api.Models.TaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeTaiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaTriConLai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("HaoMon")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("KhauHao")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguyenGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SoDanhMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiId");

                    b.ToTable("TaiSans");
                });

            modelBuilder.Entity("SciTrack.Api.Models.TrangThietBi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaTriConLai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("KhauHaoHaoMon")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LienQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaThietBi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguyenGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NhatKySuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThietBi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrangThietBis");
                });

            modelBuilder.Entity("SciTrack.Api.Models.DeTai", b =>
                {
                    b.HasOne("SciTrack.Api.Models.KetQuaDeTai", "KetQuaDeTai")
                        .WithMany()
                        .HasForeignKey("KetQuaDeTaiId");

                    b.Navigation("KetQuaDeTai");
                });

            modelBuilder.Entity("SciTrack.Api.Models.TaiSan", b =>
                {
                    b.HasOne("SciTrack.Api.Models.DeTai", "DeTai")
                        .WithMany()
                        .HasForeignKey("DeTaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");
                });
#pragma warning restore 612, 618
        }
    }
}
